#!/bin/bash
export BOARD_SETUP=1
export GCC_PREFIX=""
export GPP_PREFIX=""

export BOARD_SETUP=done
unset ARM_EMBEDDED_SYSROOT
unset ARM_EMBEDDED_INCLUDE
unset ARM_EMBEDDED_INCLUDE_EABI
export ARM_EMBEDDED_LIB_EABI=none
export CROSS_COMPILE=""





